package.json

This prevents a warning when running `npm install`

Add respository information to package.json

---

api/osm.js
stream/osm/delimited_ranges.js
test/_unit.js
test/stream/osm/delimited_ranges.js

parse delimited house number lists as per https://github.com/pelias/interpolation/issues/33
eg. iterates over `1A,1B,1C,1D,1E,1F,1G,1H,1J,1K,1L,1M,1N,1P,2A,2B,2C,2D,2E,2F,2G,2H,2J` creating one record per element in the list.
currently supports `;` and `,`

osm: parse delimited house number lists

---

Dockerfile
interpolate
readme.md

This PR refactors the Docker entry point `./interpolate` so that it can run shell script as well as node scripts.
added documentation on how to run a build using the Docker container, see `readme.md`

Dockerize builds

---

interpolate

without this code when the parent bash script dies it leaves the child processes running.
this is bad when using `upstart` or when running a build as child scripts keep running well after the bash script has died.

bin: pass SIGTERM signal to child processes

---

package.json

This removes a deprecation warning when running `npm i` and allows us to
get updates to the polyline package in the future.

Use @mapbox/polyline package

---

package.json
readme.md
test/functional/potsdamerplatz/run.js
test/lib/analyze.js
test/lib/mock_libpostal.js
test/lib/mock_libpostal_responses.json

This PR builds on https://github.com/pelias/interpolation/pull/60 to allow us to merge support for libpostal 1.0!
It updates all the mock libpostal responses for libpostal 1.0, makes it easier to configure the libpostal mocking code to update its stored responses, and adds instructions on how to do that in the readme.

Improve libpostal mocking

---

interpolate

tested with:
```bash
(curl -s http://missinglink.files.s3.amazonaws.com/new_york.gz | gunzip) | ./interpolate polyline street.db
```
also add silencer for case when no jobs have been run (ie. `./interpolate help`)

fix stdin redirection

---

readme.md

Point users to the pelias-config section of pelias/api repo for connecting the interpolation service
fixes #70

README section linking to API config instructions

---

package.json
readme.md
script/build.sh
script/conflate_osm.sh
script/conflate_tiger.sh
script/import.sh
script/js/update_tiger.js

- Adds a new node.js script for downloading TIGER data with the ability to filter by state code
- Adds the ability to read the TIGER download configuration from pelias-config
- Updates the existing build scripts to work with docker-compose
- Adds helpful logging throughout the build process
Connected to pelias/pelias#506

Make scripts work with docker-compose

---

.circleci/docker.sh

This will only skip greenkeeper branches, instead of all of them.
Connects https://github.com/pelias/dockerfiles/issues/21

Fix CircleCI code to skip builds on greenkeeper branches

---

api/tiger.js
stream/address/lookup.js

in nodejs version `4` it was possible to check `stream.writable === true` on a stream opened to a file descriptor, and if that fd was not attached then `.writable` would be `false`.
as of nodejs `6` this seems to no longer be true and so when the stream is first written, node crashes fatally with a core-dumped error.
this must be a recent change to node as our prior Travis tests were passing on 4 and 6.
this PR implements a more robust way of checking the fd is attached before writing to it.
I also fixed some line comments which were incorrect.

more robust checks to determine if fd3 is attached or not

---

Dockerfile
api/tiger.js
docker_build.sh
stream/address/lookup.js

note: rebased off https://github.com/pelias/interpolation/pull/111 please merge that PR first
external scripts reference a file called `docker_build.sh` which was being generated using an `echo` command as part of `Dockerfile`.
this PR moves that functionality to a physical file on disk so that it's easier to debug and reason about the whereabouts of that file when browsing the repo.
IMHO this workflow is a little messy and I would like to remove the `npm run build` step from here too, although I didn't yet as I'm not sure about which external scripts are depending on that behavior.

move docker_build script to file

---

Dockerfile

The `ENTRYPOINT` command seems to have been erroneously removed in https://github.com/pelias/interpolation/commit/1ede4e276e9a8b60273385837f099b11a8672377#diff-3254677a7917c6c01f55212f86c57fbf
The problem is that all the documentation expects: `ENTRYPOINT [ "./interpolate" ]`
resolves: https://github.com/pelias/interpolation/issues/117

fix Dockerfile entrypoint

---

Dockerfile
readme.md

The Dockerfile for this repo was originally written with the intention of having `--entrypoint=./interpolate`.
At [one point](https://github.com/pelias/interpolation/commit/1ede4e276e9a8b60273385837f099b11a8672377#diff-3254677a7917c6c01f55212f86c57fbf) this was changed to remove the `ENTRYPOINT` command.
So I [opened a PR](https://github.com/pelias/interpolation/pull/120) to put it back again :)
The problem is that we have documentation for both versions of ENTRYPOINT vs. no ENTRYPOINT, meaning that people are relying on it being one way or the other.
@orangejulius and I discussed it and came to the conclusion that, from now onward, we would not publish docker images with an `ENTRYPOINT`, this keeps the images consistent and predictable.
This PR removes the ENTRYPOINT and updates the …

remove docker entrypoint

---

stream/street/augment.js

in the case where the `.0sv` extract contains a line which doesn't have a valid name, we currently throw a fatal error.
this PR changes that behavior to a warning so that one or two bad eggs don't spoil the whole bunch.
resolves: https://github.com/pelias/interpolation/issues/127

improved error handling for polylines missing a valid name

---

readme.md
script/js/update_tiger.js

allow filtering by county code, improve config parsing logic and handling of zero padding for integer values
resolves: https://github.com/pelias/interpolation/issues/142

allow filtering by county code

---

.travis.yml
package.json
readme.md

This adds Node.js 10 to the TravisCI build matrix, but allows it to fail for now.

CI cleanup

---

readme.md
stream/address/lookup.js
test/functional/action.js

this PR fixes support for OSX (bad file descriptor errors) and also documents that GDAL is required for TIGER and how to go about installing it.
related: https://github.com/pelias/interpolation/pull/111

Fix support for OSX

---

bin/funcs
bin/units
package.json

The way we were running our unit tests does not catch fatal errors in the unit test run, even though they return non-zero status codes.
By using a dedicated script to run the tests, with the `pipefail` option, we can catch them.
Connects https://github.com/pelias/pelias/issues/744

feat(test): Run tests in dedicated script to catch errors

---

bin/download-tiger
docker_build.sh
package.json

By using dedicated scripts to start downloads and the interpolation service, we can avoid several issues encountered in Docker containers:
- `npm` does not pass signals, so by avoiding `npm start` and using `exec` to minimize extra "layers" of shell scripts, we can ensure our containers stop quickly when told to stop.
- `npm` requires write access to the root filesystem. We wish to avoid that requirement.
For this project, we also use `exec` in `docker_build.sh` to avoid a call to `npm`.
Connects https://github.com/pelias/pelias/issues/745

Support read-only root filesystem in Docker containers

---

script/js/update_tiger.js

Many people wish to skip the interpolation TIGER download in projects such as `pelias/docker`, where the interpolation engine is configured to run by default.
Currently, there is no way to tell the downloader to skip downloading _any_ data. This PR makes it so that if there is no `imports.interpolation.download.tiger` section at all in `pelias.json`, the downloader will take no action.
An empty object for that key in `pelias.json` will still download all TIGER data.
Connects https://github.com/pelias/docker/issues/5

feat(tiger): Download nothing instead of all if no config present

---

lib/analyze.js
test/lib/analyze.js

support for the following house number formats:
- `240 4t`
- `27, 2º, 4ª`
resolves #199

improved support for Spanish addresses

---

lib/analyze.js
test/lib/analyze.js

handle non-latin apartment characters by first normalizing them to latin (eg. `18Č`)
as mentioned in https://github.com/pelias/interpolation/issues/195

remove diacritics for non-latin languages

---

script/build.sh

This change allows users to run build.sh with a custom PBF2JSON_BIN ENV, i.e. to work around issue
pelias/interpolation#73.

build.sh: allow ENV PBF2JSON_BIN to be set

---

Dockerfile

Ubuntu comes with an extremely old (circa 1996) version of awk which
apparently has some performance regressions.
By updating to the latest version we can mitigate _some_ of the
slowness of building interpolation database.
Connects https://github.com/pelias/interpolation/issues/211

feat(Dockerfile): Update to a modern version of awk

---

package.json
script/js/adapter/CensusFTP.js
script/js/adapter/CensusS3Mirror.js
script/js/update_tiger.js
test/_unit.js
test/script/js/adapter/CensusFTP.js
test/script/js/adapter/CensusS3Mirror.js

This PR attempts to fix issues reported with downloads from the Census FTP server (which has always caused us headaches)
- abstract download source using adapter pattern
- add s3 mirror source
I've created an abstract interface which will allow us to add new sources in the future, or switch sources as need be.
I also added an adapter for the [Census Mirror Ian set up](https://census-backup.s3.amazonaws.com/index.html), we will use that from now on.
resolves https://github.com/pelias/docker/issues/135
resolves https://github.com/pelias/interpolation/issues/133
related https://github.com/pelias/interpolation/issues/219

abstract TIGER download source using adapter pattern

---

readme.md

When running a script inside a Docker container with a parameter that references a file,
the file path must point to the file in the container, not to the file in the host.

readme: fix usage example for ./interpolate server

---

demo/index.html
demo/map.css

- changes search box placeholder to "search to center map"
- hides the input / street box until a street is clicked
- adds "click a street to see data" instructions if no street has been
clicked
- puts a 123 placeholder in the interpolation number box
on load:
after click

minor changes to make demo frontend easier to use

---

package.json
script/conflate_tiger.sh
script/js/update_tiger.js
script/update_tiger.sh

I'm getting tired of seeing `npm unzip` issues, so 👋 bye bye module 👋 
Many years ago when I wrote this code I didn't know about [GDAL virtual filesystems](https://gdal.org/user/virtual_file_systems.html) and assumed that zip files are easy, and streamable, which it turns out they aren't 🤷‍♂ 
This PR greatly simplifies the code by downloading the `.zip` files and then... wait for it... **not** decompressing them 😱 
The only process reading these files is `ogr2ogr` and it'll just as happily read ZIP files as it would the SHP files.
Good news is we can delete the npm module and also the `shapefiles` directory in the process.

delete npm unzipper, replace with GDAL virtual filesystem

---

package.json

Extracted from other recent PRs. This allows us to support actually running the interpolation service on Node.js 12
If we end up merging something like #146 which unbundles the libpostal service from this repo, then we won't not need this any more, but it's a small enough change that it's worth it.
Connects https://github.com/pelias/pelias/issues/800

feat(package): use node-postal module compatible with node12

---

docs/conflation.md
docs/design-doc.md
docs/existing-standards.md
docs/introduction.md
readme.md

In order to allow us to deprecate the pelias/pelias wiki, this moves all interpolation related documentation to this repository.
GitHub wikis are a bit of a niche feature, which means any information in there is hard to find.
Additionally, because they don't notify us when changes are made (in comparison to the normal pull request workflow of documentation stored in a git repository proper), we have no idea what the state of anything is.
The interpolation design and introduction docs are some of the few truly valuable pages in our wiki, so this moves them to a better place.

Move documentation from Pelias Wiki to this repo

---

package.json
script/js/update_tiger.js

In this project, we only use the fs-extra package for its `mkdir -p` style convenience wrapper, which can now easily be done with the stock fs module.
This change removes usage of the fs-extra module and replaces it withthe native recursive option.
Closes https://github.com/pelias/interpolation/pull/251

feat(deps): Remove fs-extra module

---

cmd/server.js

This PR adds a new property `projection` to the `nearby` endpoint which returns the projected point-on-line.

update nearby endpoint to return projected point-on-line

---

cmd/server.js
readme.md

---
* Added support for overriding the default network address to bind to via the HOST environment variable, in line with (almost) all of the other Pelias services.
---
* Update `cmd/server.js` adding support for the HOST env var and passing this to `app.listen()`
* Small update to `README.md` documenting this
---
Without `HOST` defined ...
```
PORT=4300 ./interpolate server address.db street.db
server listening on 0.0.0.0:4300
```
```
sudo lsof -i -P -n | grep LISTEN | grep 4300
node      92897          pelias   24u  IPv6 512879      0t0  TCP *:4300 (LISTEN)
```
With `HOST` defined ...
```
HOST=127.0.0.1 PORT=4300 ./interpolate server address.db street.db
server listening on 127.0.0.1:4300
```
```
sudo lsof -i -P -n | grep LISTEN | grep 4300
node      92917          pelias   24u  IPv4 …
```

Add host address env var override and update README

---

script/js/adapter/CensusS3Mirror.js

Our existing TIGER HTTP mirror is not longer active (https://census-backup.s3.amazonaws.com/).
I've synced the data to the GeocodeEarth CDN so we don't have issues in the future.
I've uploaded both the `2016` and `2019` files for when we decide to upgrade.
- https://data.geocode.earth/uscensus/geo/tiger/TIGER2016/ADDRFEAT/index.html
- https://data.geocode.earth/uscensus/geo/tiger/TIGER2019/ADDRFEAT/index.html

change TIGER data mirror to GeocodeEarth CDN

---

docker_build.sh

this PR modernizes the `docker_build.sh` script which is the generic entrypoint for docker-compose projects.
I migrated the ticket https://github.com/pelias/interpolation/issues/267 from another repo today and when I went to fix it I noticed the script could do with some updates:
- avoid parsing output of `ls` (as per https://github.com/pelias/polylines/commit/26686d8356226c4e15a79634db51079a54931800)
- loosen the PBF extension pattern from `*.osm.pbf` to `*.pbf` (as per https://github.com/pelias/interpolation/issues/267)
- add a bunch of errors and warnings to help users identify potential issues
closes: https://github.com/pelias/interpolation/issues/267

update docker_build.sh script

---

.github/workflows/push.yml
api/near.js
package.json

this PR matches a bunch of similar ones in other repos where the version of `better-sqlite3` has been upgraded to the latest version, this removes the need to link to my branch and also adds support for recent versions of nodejs.
closes: https://github.com/pelias/interpolation/pull/257, but may require [enabling unsafe mode](https://github.com/JoshuaWise/better-sqlite3/blob/master/docs/unsafe.md)

Upgrade better-sqlite3 to latest version (v7.4.3)

---

package.json

I guess we know where we originally copied the `package.json` file from when starting the interpolation project years ago :)

Update homepage URL in package.json

---

stream/oa/convert.js

simple, partial fix for the issue mentioned in https://github.com/pelias/interpolation/issues/278
this PR simply changes the logger to write *only* the error message and not the whole stack.
the log files contain many entries such as the one below, the stack itself isn't useful and the corresponding line number can be found easily with `git grep 'invalid csv row Error'` as its the only occurrence in the repo.
I expect that this minor change will significantly reduce the log size, at least for addresses with an empty `NUMBER` or `STREET` field.
```bash
invalid csv row Error: invalid street
at Address.setStreet (/code/interpolation/lib/Address.js:71:11)
at DestroyableTransform._transform (/code/interpolation/stream/oa/convert.js:37:15)
at DestroyableTransform.Transform._read …
```

feat(logging): reduce log verbosity

---

demo/index.html

at some point the marker images used for the demo changed to include an inner white circle which makes reading the house numbers very difficult.
this PR simply changes the image version number from `3->2` which resolves the issue and reverts to the previous style:

demo: use solid markers

---

demo/index.html

Sometimes its useful to be able to zoom in quite a bit when inspecting the exact location of addresses in the demo.
The Leaflet default is to max out at zoom 18. This increases that value to 25, quite a bit closer.

Increase Leaflet `maxZoom` to 25

---

Dockerfile
test/test_libpostal.js

The [node-postal](https://github.com/openvenues/node-postal) NPM module requires a full C++ compiler toolchain _and_ python3 to install. After pelias/docker-baseimage#23 and pelias/docker-libpostal_baseimage#5 this toolchain is no longer present in our Docker baseimage.
This PR uses a Docker multi-stage build to build _just_ the NPM modules required by the interpolation service while a C++ toolchain is present.
The `node_modules` directory can then be copied to the final image without needing a C++ toolchain or python to be present.
In addition to saving some space in the final image, this fixes issues people were having with our Docker images, since `node-postal` wasn't functional.
Fixes pelias/docker#271

fix(Docker): Use multi-stage build to handle node-postal dependencies 

---

script/js/update_tiger.js

the current log output when downloading TIGER files is very verbose and at the same time not super informative
```
info: [interpolation(TIGER)] Queuing 1 downloads
info: [interpolation(TIGER)] Downloading tl_2021_41051_addrfeat.zip
info: [interpolation(TIGER)] Queuing 1 downloads
info: [interpolation(TIGER)] Downloading tl_2021_41005_addrfeat.zip
info: [interpolation(TIGER)] Queuing 1 downloads
info: [interpolation(TIGER)] Downloading tl_2021_41071_addrfeat.zip
info: [interpolation(TIGER)] Queuing 1 downloads
info: [interpolation(TIGER)] Downloading tl_2021_41047_addrfeat.zip
info: [interpolation(TIGER)] Queuing 1 downloads
info: [interpolation(TIGER)] Downloading tl_2021_41053_addrfeat.zip
info: [interpolation(TIGER)] Queuing 1 downloads
info: [interpolation(TIGER)] Downloading …
```

downloads: improve logger messages

---

script/js/update_tiger.js

following on from https://github.com/pelias/interpolation/pull/286 the completion message is still too verbose:
```
Creating pelias_interpolation_run ... done
info: [interpolation(TIGER)] downloaded tl_2021_41067_addrfeat.zip
info: [interpolation(TIGER)] downloads complete
info: [interpolation(TIGER)] downloaded tl_2021_41051_addrfeat.zip
info: [interpolation(TIGER)] downloads complete
info: [interpolation(TIGER)] downloaded tl_2021_41005_addrfeat.zip
info: [interpolation(TIGER)] downloads complete
info: [interpolation(TIGER)] downloaded tl_2021_41071_addrfeat.zip
info: [interpolation(TIGER)] downloads complete
info: [interpolation(TIGER)] downloaded tl_2021_41047_addrfeat.zip
info: [interpolation(TIGER)] downloads complete
info: [interpolation(TIGER)] downloaded …
```

downloads: improve logger completion message

---

package.json

This PR explicitly upgrades the dependency on `node-postal` to require version 1.1.2 or greater.
That version adds support for Node.js 16 via https://github.com/openvenues/node-postal/pull/37.
I did some testing and can confirm that when pinned to node-postal 1.1.1, a Node.js 16 Docker image does _not_ correctly build libpostal, but with 1.1.2 the node-postal module is built and works correctly.
While our version range specifier means that node-postal 1.1.2 would have been brought in, it seems worth it to explicitly require it as we move towards Node.js 16 support everywhere.

Upgrade to node-postal 1.1.2 for Node.js 16 support

---

.github/workflows/_test.yml
.github/workflows/push.yml

This PR includes a bunch of commits made by a script that standardizes as much as possible our CI config across all repositories.
Along the way it also ensures we test all Node.js versions that are an LTS release, not EOL, and currently work with this repository. Any Github Actions that were out of date or used old Node.js versions (checkout and setup-node @v2) are also updated.
For the interpolation repository that means Node.js 18 only, as we have to upgrade node-postal to v1.20 for Node.js 20 support. Similarly we need to update better-sqlite3 for Node.js 22 support.
Also, the CI OS version is now hardcoded to `ubuntu-22.04`. We fooled around with an organization wide CI variable to configure that, but it broke CI in forks and doesn't really help us much, so it's now undone.
If there …

Update CI to conform to a standard template and test all supported, non-EOL LTS Node.js releases

---

package.json

This is required for newer Node.js version support
https://github.com/pelias/pelias/issues/950

Update better-sqlite3 to v11.5.0

---

.github/workflows/_test.yml
package.json

This allows us to use libpostal bindings with Node.js 22+
https://github.com/pelias/pelias/issues/950

Upgrade node-postal to 1.3.0

---

package.json

This helps with easier installation on Mac and other ARM platforms when using newer Node.js versions.

Upgrade better-sqlite3 to v12.2.0
